### ISSUE TITLE
Auto update the "Prerequisites" section of the readme

### ISSUE THREAD

**Issue by TrueBabyChaise** [0Nom4D/mdCreator#5]
Update the "Prerequisites" section with the language enter with the -l option, it would very convenient and more easy to use for lazy people like me

**Comment by 0Nom4D** [comment]
Feature will be added to mdCreator in the next update.

Thanks for report!

**Comment by 0Nom4D** [comment]
Issue is closed due to pull request #6.
Thanks for contributing!
